### ISSUE TITLE
Enhancement of website content

### ISSUE THREAD

**Issue by utkarshluthra** [ank1traj/cucoders#9]
| Name | About | Title | Labels | Assignee |
| --- | --- | --- | --- | --- |
| Updating Website content | Changing the text on the website to make it look better and more appropriate | Improvement of website content | `enhancement` `content` `text` | @utkarshluthra |

## Enhancement

**Is your feature request related to a problem?**
The content on the website seems very formal and plagiarised

**Describe the solution you'd like**
Writing content in a more professional and descriptive form such that it can be easier for the user. Making content more appropriate.

**Describe alternatives you've considered**
NA

**Teachability, Documentation, Adoption, Migration Strategy**
NA

**Comment by ank1traj** [comment]
The issue has been fixed so closing the issue.
